version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:b63a849cba58acf342a4ee9f76c2ef0ddf207dd2"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-gatewayrs:28c08e2c6d21bcc628cbf0415e4c1d155f9fa192"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:36a9a0b3d66bc29b4a5927e9410c803a360c4c5d"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: "nebraltd/hm-upnp:a25dbac8f42b256e9551fafc924b06f5f51ebf32"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'
      
volumes:
  miner-storage:
  miner-log:
  pktfwdr:
