version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:48ebe25776f4d7d9714da5ef7b00e9934b1edacc"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-gatewayrs:28c08e2c6d21bcc628cbf0415e4c1d155f9fa192"


volumes:
  miner-storage:
  miner-log:
  pktfwdr:
