version: '2'

services:

  gateway-config:
    image: "nebraltd/hm-config:61b77e8011413d19aa36c9bb681df0d48c054fbd"
    environment:
      - 'FIRMWARE_VERSION=2021.08.02.1_LIGHT'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:c12a73944d23bba92e57cdd87043d56fe0b37819"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-gatewayrs:759e971dcb3413435205182999656cf5a1bbe911"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'

  diagnostics:
    image: "nebraltd/hm-diag:8d4c300237e559e2c1b6e873a4f5b09f78cdfdad"
    environment:
      - 'FIRMWARE_VERSION=2021.08.02.1_LIGHT'
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:80'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.dbus: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:9a1e553899ca95edb8d14afee4c105c1950bcc0e"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: "nebraltd/hm-upnp:4235b4175587fceab5e79c4e4790f1ff8da34bba"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'
      
volumes:
  miner-storage:
  miner-log:
  pktfwdr:
