version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:cd751008a1e3ecfc0be04384f68b2c2bd10199f5
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.16.1
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=tcp:host=localhost,port=55884
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:477eeda57ca9ebcb3909eebb8e869776a95b1668
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd

  helium-miner:
    image: nebraltd/hm-miner:cbe7f7ea803f2aa7d435419725810ef55fd7dde4
    depends_on:
      - dbus-session
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=tcp:host=dbus-session,port=55884
      - RELEASE_BUMPER=foobar

  diagnostics:
    image: nebraltd/hm-diag:93363e4ad0ad0042043c7306eb0dc4c5fa5dda08
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.16.1
      - DBUS_SESSION_BUS_ADDRESS=tcp:host=dbus-session,port=55884
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  gwmfr:
    image: nebraltd/hm-gwmfr:f84834b70e34520e63d4a2dda521a198feb66b71
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: nebraltd/hm-upnp:4e419f5bb5d59b31fcd1f81e0c94f7e94cd9ebee
    network_mode: "host"
    restart: on-failure
    volumes:
      - pktfwdr:/var/pktfwd

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    expose:
      - "55884"

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
