version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:ed87124325e75b19d3b2774a48f9504f193206c3"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
