version: '2'

services:

  gateway-config:
    image: "nebraltd/hm-config:87ae525d2213120686cdeb4872825ef74f2757c3"
    depends_on:
      - dbus-system
    environment:
      - 'FIRMWARE_VERSION=2021.09.07.0_LIGHT'
      - 'DBUS_SYSTEM_BUS_ADDRESS=tcp:host=dbus-system,port=55884'
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.dbus: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:e2074a266c0edba2b10c5f8d5dc150047bd92432"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-miner:2987e2936dab8c9f89c5fd719417c62263a1f5e7"
    depends_on:
      - dbus-system
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=tcp:host=dbus-system,port=55884'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'

  diagnostics:
    image: "nebraltd/hm-diag:91885139deaf905a5ff91aee10aea9495951a3d0"
    depends_on:
      - dbus-system
    environment:
      - 'FIRMWARE_VERSION=2021.09.07.0_LIGHT'
      - 'DBUS_SYSTEM_BUS_ADDRESS=tcp:host=dbus-system,port=55884'
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:5000'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.supervisor-api: '1'

  gwmfr:
    image: "nebraltd/hm-gwmfr:f84834b70e34520e63d4a2dda521a198feb66b71"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: "nebraltd/hm-upnp:4e419f5bb5d59b31fcd1f81e0c94f7e94cd9ebee"
    network_mode: "host"
    restart: on-failure
    volumes:
      - 'pktfwdr:/var/pktfwd'

  dbus-system:
    image: "nebraltd/hm-dbus:c4787932ae7efb869876228cc1107e09088fc836"
    restart: always
    environment:
      - 'DBUS_CONFIG=system.conf'
    labels:
      io.balena.features.dbus: '1'
      
volumes:
  miner-storage:
  miner-log:
  pktfwdr:
