version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:d624b84cb937873ce44b1ba95f14bc87aaeb5492"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  helium-miner:
    image: "nebraltd/hm-gatewayrs:28c08e2c6d21bcc628cbf0415e4c1d155f9fa192"
    ports:
      - "44158:44158/tcp"
      - "1680:1680/udp"
    volumes:
      - 'miner-storage:/var/data'
      - 'miner-log:/var/log/miner'
      - 'pktfwdr:/var/pktfwd'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
      - 'RELEASE_BUMPER=foobar'
    labels:
      io.balena.features.dbus: '1'

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
