version: '2'

services:

  gateway-config:
    image: nebraltd/hm-config:c50addcbcbc33f094168497db1b2653490211518
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.27.0
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    privileged: true
    network_mode: "host"
    cap_add:
      - NET_ADMIN
    volumes:
      - miner-storage:/var/data
      - dbus:/session/dbus
    labels:
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.dbus: '1'
    stop_signal: SIGINT

  packet-forwarder:
    image: nebraltd/hm-pktfwd:29a7dde35ad8b02c7eab570d325d9124bcb86688
    privileged: true
    volumes:
      - pktfwdr:/var/pktfwd

  helium-miner:
    image: nebraltd/hm-miner:70dbc27b98c233e969001f8e3bb91371a3ef7bdb
    depends_on:
      - dbus-session
    expose:
      - "1680"
      - "4467"
    ports:
      - "44158:44158/tcp"
    volumes:
      - miner-storage:/var/data
      - miner-log:/var/log/miner
      - pktfwdr:/var/pktfwd
      - dbus:/session/dbus
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    environment:
      - DBUS_SYSTEM_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
      - RELEASE_BUMPER=foobar

  diagnostics:
    image: nebraltd/hm-diag:b1b9eb24903f9b2e101f85894599f2a849f36c6a
    depends_on:
      - dbus-session
    environment:
      - FIRMWARE_VERSION=2021.09.27.0
      - DBUS_SESSION_BUS_ADDRESS=unix:path=/session/dbus/session_bus_socket
    volumes:
      - pktfwdr:/var/pktfwd
      - miner-storage:/var/data
      - dbus:/session/dbus
    ports:
      - "80:5000"
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  gwmfr:
    image: nebraltd/hm-gwmfr:f84834b70e34520e63d4a2dda521a198feb66b71
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: on-failure

  upnp:
    image: nebraltd/hm-upnp:4e419f5bb5d59b31fcd1f81e0c94f7e94cd9ebee
    network_mode: "host"
    restart: on-failure
    volumes:
      - pktfwdr:/var/pktfwd

  dbus-session:
    image: balenablocks/dbus:rpi-0.0.2
    restart: always
    volumes:
      - dbus:/session/dbus
    environment:
      - DBUS_ADDRESS=unix:path=/session/dbus/session_bus_socket

volumes:
  miner-storage:
  miner-log:
  pktfwdr:
  dbus:
