version: '2'

services:

  packet-forwarder:
    image: "nebraltd/hm-pktfwd:b76d2ed6da11b316a766da75c49a694413cc29a8"
    privileged: true
    volumes:
      - 'pktfwdr:/var/pktfwd'

  diagnostics:
    image: "nebraltd/hm-diag:ad01b46cce98b75cf43be3c800981d9de07c9b2d"
    volumes:
      - 'pktfwdr:/var/pktfwd'
      - 'miner-storage:/var/data'
    ports:
      - '80:80'
    cap_add:
      - SYS_RAWIO
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    labels:
      io.balena.features.sysfs: '1'

  helium:
    image: "nebraltd/hm-gatewayrs:b826e5cc45804600b672dd9fc75fe5bbed2031ee"

  gateway-config:
    image: "nebraltd/hm-config:35d36ab43371e703fc78ec34892d5e56b9d70b37"
    privileged: true
    network_mode: "host"
    cap_add:
            - NET_ADMIN
    volumes:
      - 'miner-storage:/var/data'
    environment:
      - 'DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket'
    labels:
      io.balena.features.dbus: '1'
      io.balena.features.sysfs: '1'
      io.balena.features.kernel-modules: '1'
      io.balena.features.supervisor-api: '1'
    stop_signal: SIGINT


volumes:
  miner-storage:
  miner-log:
  pktfwdr:
